package yolo.ioopm.mud.communication;

public enum MessageType {
	GENERAL_ACTION,
	GENERAL_ERROR,
	GENERAL_REPLY,
	HEARTBEAT,
	HEARTBEAT_REPLY,
	AUTHENTICATION,
	AUTHENTICATION_REPLY,
	SERIOUS_ERROR,
	REGISTRATION,
	REGISTRATION_REPLY,
	NEW_CONNECTION
}
