package yolo.ioopm.mud.communication;

public enum MessageType {
	GENERAL_ACTION,
	GENERAL_ERROR,
	GENERAL_REPLY,
	HEARTBEAT,
	AUTHENTICATION,
	HEARTBEAT_REPLY,
	NEW_CONNECTION,
	AUTHENTICATION_REPLY
}
