package yolo.ioopm.mud.communication;

public enum MessageType {
	GENERAL_ACTION,
	GENERAL_ERROR,
	GENERAL_REPLY,
	HEARTBEAT,
	AUTHENTICATION,
	HEARTBEAT_REPLY, 
	AUTHENTICATION_REPLY,
	SERIOUS_ERROR
}
